# Generated by Django 4.0.4 on 2022-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=60, null=True, unique=True)),
                ('veh_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registration',
                'db_table': 'registration',
                'ordering': ['email_address'],
            },
        ),
        migrations.CreateModel(
            name='vehicleIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_number', models.CharField(blank=True, max_length=20, null=True)),
                ('inTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle In',
                'verbose_name_plural': 'Vehicle Ins',
                'db_table': 'vehicleIn',
                'ordering': ['veh_number'],
            },
        ),
        migrations.CreateModel(
            name='vehicleOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_number', models.CharField(blank=True, max_length=20, null=True)),
                ('outTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle Out',
                'verbose_name_plural': 'Vehicle Outs',
                'db_table': 'vehicleOut',
                'ordering': ['veh_number'],
            },
        ),
        migrations.CreateModel(
            name='vehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(blank=True, max_length=20, null=True)),
                ('veh_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vehicle Status',
                'verbose_name_plural': 'Vehicle Status',
                'db_table': 'vehicleStatus',
                'ordering': ['slot'],
            },
        ),
    ]
