# Generated by Django 4.0.4 on 2022-06-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclein',
            options={'verbose_name': 'Vehicle In', 'verbose_name_plural': 'Vehicle Ins'},
        ),
        migrations.AlterModelOptions(
            name='vehicleout',
            options={'verbose_name': 'Vehicle Out', 'verbose_name_plural': 'Vehicle Outs'},
        ),
        migrations.AlterField(
            model_name='vehiclein',
            name='veh_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleout',
            name='veh_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='veh_number',
            field=models.CharField(blank=True, default='XXX', max_length=12, null=True),
        ),
    ]
