# Generated by Django 4.0.4 on 2022-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_rfid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('veh_number', models.CharField(blank=True, max_length=30, null=True)),
                ('rfiid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle-Rfid',
                'verbose_name_plural': 'Vehicle-Rfids',
                'db_table': 'vehicle_rfid',
            },
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
