# Generated by Django 4.0.4 on 2022-07-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0005_rename_rfiid_vehicle_rfid_rfid_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_number', models.CharField(blank=True, max_length=30, null=True)),
                ('rfid_no', models.CharField(blank=True, max_length=100, null=True)),
                ('desciption', models.TextField(blank=True, max_length=200, null=True)),
                ('veh_info_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
