# Generated by Django 4.0.4 on 2022-07-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='veh_info_pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='veh_info_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
