# Generated by Django 4.0.4 on 2022-07-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_remove_customer_veh_info_pic_customer_veh_info_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='desciption',
            new_name='description',
        ),
    ]
